### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#73]
Subject: feedback on week 9 project progress

See [v1.2 progress guide](https://nuscs2113-ay1819s2.github.io/website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Follow up from v1.1

- [x]  Auto-publishing set up for the team repo and the website is available at [link](https://CS2113-AY1819S2-M11-2.github.io/main) (:heavy_check_mark: well done!)
* README page:
     -  [ ]  Parts not related to your product are removed (:exclamation: try to do by next milestone)
     -  [x]  se-edu/addressbook-level[3/4] acknowledged (:heavy_check_mark: well done!)
     -  [x]  `Ui.png` has been updated (:heavy_check_mark: well done!)

### Recommended progress for v1.2

-  [x]  Issue labels<sup>*</sup> set up e.g., `type.*` and `priority.*` (:heavy_check_mark: well done!)
-  [x]  All milestones `v1.2`, `v1.3`, `v1.4`, created (:heavy_check_mark: well done!)
-  [x]  Issues marked as `type.Story` e.g., [link](https://github.com/CS2113-AY1819S2-M11-2/main/issues/20) (:heavy_check_mark: well done!)
-  [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/CS2113-AY1819S2-M11-2/main/pull/4) (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
     -  [x]  A suitable deadline<sup>**</sup> set (:heavy_check_mark: well done!)
     -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/CS2113-AY1819S2-M11-2/main/issues/20) (:heavy_check_mark: well done!) 
     -  [ ]  All issues/PRs in it are closed/merged  (:exclamation: try to do by next milestone) 
     -  [x]  Milestone closed (:heavy_check_mark: well done!) 
     -  [x]  Code tagged as `v1.2` (:heavy_check_mark: well done!) 
-  [x]  Build passing [link](https://travis-ci.org/CS2113-AY1819S2-M11-2/main/builds/507508540) (:heavy_check_mark: well done!)
-  [x]  Some issues assigned to milestone v1.3 e.g., [link](https://github.com/CS2113-AY1819S2-M11-2/main/issues/11) (:heavy_check_mark: well done!)

 <sup>*</sup>Remember to use the format specified, else it will not be picked up by the bot
<sup>**</sup>Remember that the deadline is the midnight before your tutorials

Not graded:
- [x] Updated User Guide for v1.2  (:+1:  Kudos!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [ ]  Has issues/PRs assigned for the milestone (:exclamation: try to do by next milestone)

### Follow up from v1.1

* Used forking workflow:
     -  [x]  Created PRs [link](https://github.com/CS2113-AY1819S2-M11-2/main/pull/3) (:heavy_check_mark: well done!)
     -  [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `shengkok.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

Tutor: @devamanyu

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-03-18 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.

**Comment by devamanyu** [comment]
Hi @khairulhazril, @nicholasleeeee, @Shengkok, @Justin-Ong ,

Kindly remove the `Learning Outcomes` link from your Readme to get a check at the `Parts not related to your product are removed` in the next milestone v1.3

Also, in v1.2 I could see one of the issues is still open. Consider closing/merging issues to any milestone upon its due date.
